//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaProject.API.Infrastructure.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzaProject.API.Infrastructure.Localizations.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required field..
        /// </summary>
        public static string AddressCityEmpty {
            get {
                return ResourceManager.GetString("AddressCityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be less than 16 symbols..
        /// </summary>
        public static string AddressCityLengthInvalid {
            get {
                return ResourceManager.GetString("AddressCityLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required field..
        /// </summary>
        public static string AddressCountryEmpty {
            get {
                return ResourceManager.GetString("AddressCountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country must be less than 16 symbols..
        /// </summary>
        public static string AddressCountryLengthInvalid {
            get {
                return ResourceManager.GetString("AddressCountryLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 100 symbols..
        /// </summary>
        public static string AddressDescriptionLengthInvalid {
            get {
                return ResourceManager.GetString("AddressDescriptionLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address does not exist for this user..
        /// </summary>
        public static string AddressDoesNotExist {
            get {
                return ResourceManager.GetString("AddressDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find address..
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region must be less than 16 symbols..
        /// </summary>
        public static string AddressRegionLengthInvalid {
            get {
                return ResourceManager.GetString("AddressRegionLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t exist..
        /// </summary>
        public static string AddressUserIdDoesNotExist {
            get {
                return ResourceManager.GetString("AddressUserIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required field..
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank must be from 1 to 10..
        /// </summary>
        public static string InvalidRank {
            get {
                return ResourceManager.GetString("InvalidRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza list is required for creating order..
        /// </summary>
        public static string OrderPizzaListEmpty {
            get {
                return ResourceManager.GetString("OrderPizzaListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required field..
        /// </summary>
        public static string OrderUserIdEmpty {
            get {
                return ResourceManager.GetString("OrderUserIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza calory count is a mandatory field..
        /// </summary>
        public static string PizzaCaloryCountEmpty {
            get {
                return ResourceManager.GetString("PizzaCaloryCountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calory count must be greater than 0..
        /// </summary>
        public static string PizzaCaloryCountInvalid {
            get {
                return ResourceManager.GetString("PizzaCaloryCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than 100 characters..
        /// </summary>
        public static string PizzaInvalidDescriptionLength {
            get {
                return ResourceManager.GetString("PizzaInvalidDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is a mandatory field for pizza..
        /// </summary>
        public static string PizzaNameEmpty {
            get {
                return ResourceManager.GetString("PizzaNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza name must be at least 3 and maximum 20 symbols..
        /// </summary>
        public static string PizzaNameInvalidLength {
            get {
                return ResourceManager.GetString("PizzaNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find this pizza..
        /// </summary>
        public static string PizzaNotFound {
            get {
                return ResourceManager.GetString("PizzaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is a mandatory field for pizza..
        /// </summary>
        public static string PizzaPriceEmpty {
            get {
                return ResourceManager.GetString("PizzaPriceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than 0..
        /// </summary>
        public static string PizzaPriceInvalid {
            get {
                return ResourceManager.GetString("PizzaPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has never ordered this pizza..
        /// </summary>
        public static string RankHistoryInvalidPizzaId {
            get {
                return ResourceManager.GetString("RankHistoryInvalidPizzaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza ID is required to create rank history..
        /// </summary>
        public static string RankHistoryPizzaIdRequired {
            get {
                return ResourceManager.GetString("RankHistoryPizzaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required for ranking..
        /// </summary>
        public static string RankHistoryUserIdRequired {
            get {
                return ResourceManager.GetString("RankHistoryUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank is required field..
        /// </summary>
        public static string RankIsRequired {
            get {
                return ResourceManager.GetString("RankIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank not found..
        /// </summary>
        public static string RankNotFound {
            get {
                return ResourceManager.GetString("RankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required field..
        /// </summary>
        public static string UserFirstNameEmpty {
            get {
                return ResourceManager.GetString("UserFirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name should be at least 2 and maximum 20 characters..
        /// </summary>
        public static string UserFirstNameInvalidLength {
            get {
                return ResourceManager.GetString("UserFirstNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required field..
        /// </summary>
        public static string UserLastNameEmpty {
            get {
                return ResourceManager.GetString("UserLastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should be at least 2 and maximum 30 characters..
        /// </summary>
        public static string UserLastNameInvalidLength {
            get {
                return ResourceManager.GetString("UserLastNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required field..
        /// </summary>
        public static string UserPhoneNumberEmpty {
            get {
                return ResourceManager.GetString("UserPhoneNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must contain 9 digits..
        /// </summary>
        public static string UserPhoneNumberInvalid {
            get {
                return ResourceManager.GetString("UserPhoneNumberInvalid", resourceCulture);
            }
        }
    }
}
